bookers1/config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

bookers1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers1/app/models/book.rb
class Book < ApplicationRecord
  # 入力フォームのvalidationの設定をオンにする
  validates :title, presence: true
  validates :body, presence: true
end

bookers1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

bookers1/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
  end

## createアクションとupdateアクションの挙動の違いに注意
  def create
    @book = Book.new(book_params)
    @books = Book.all
    if @book.save  # 保存が成功したかで分岐
      flash[:notice] = "Book was successfully created"
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params) # 更新が成功したかで分岐
      flash[:notice] = "Book was successfully created"
      redirect_to book_path
    else
      render :edit
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

bookers1/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

bookers1/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers1/app/helpers/books_helper.rb
module BooksHelper
end

bookers1/app/helpers/homes_helper.rb
module HomesHelper
end

bookers1/app/views/books/edit.html.erb
<header>
  <h2>Editing Book</h2>
</header>

<main>
  <!--エラーボックス-->
  <% if @book.errors.any? %>
    <div class="error-box">
      <p class="error-box-title"><%= @book.errors.count %> errors prohibited this book from being saved:</p>
      <div class="error-box-message">
        <ul>
        <% @book.errors.full_messages.each do |massage| %>
        <li><%= massage %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  
  <!--エラーありなしで分岐している-->
  <div class="create-form">
    <%= form_with model: @book, url: book_path, method: :patch do |f| %>
      <% if @book.errors.where(:title).empty? %> <!-- エラーがない場合 -->
        <p class="create-form-title">Title<p>
        <%= f.text_field :title , class:"text-area" %>
      <% else %> <!-- エラーがある場合 -->
        <p class="create-form-title create-form-error-title">Title</p>
        <div class="create-form-error-box">
          <%= f.text_field :title , class:"text-area" %>
        </div>
      <% end %>

      <% if @book.errors.where(:body).empty? %> <!-- エラーがない場合 -->
        <p class="create-form-title">Body</p>
        <%= f.text_area :body , class:"text-area" %>
      <% else %> <!-- エラーがある場合 -->
        <p class="create-form-title create-form-error-title">Body</p>
        <div class="create-form-error-box">
          <%= f.text_area :body , class:"text-area" %>
        </div>
      <% end %>
      <div class="create-book-button">
        <%= f.submit "Update Book", class:"submit-button" %>
      </div>
    <% end %>
  </div>

<!--各ページへの-->
  <%= link_to "Show", book_path %>
  <%= link_to "Back", books_path %>
</main>

bookers1/app/views/books/index.html.erb
<header>
  <h2>Books</h2>
</header>

<main>
  <!--データベースのデータをテーブル表記にする。-->
  <table>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to "Show", book_path(book.id) %></td>
        <td><%= link_to "Edit", edit_book_path(book.id) %></td>
        <td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?"   %></td>
      </tr>
    <% end %>
    </tr>
  </table>

  <div class="new_book">
    <h3>New book</h3>
    <!--エラーボックス-->
    <% if @book.errors.any? %>
      <div class="error-box">
        <p class="error-box-title"><%= @book.errors.count %> errors prohibited this book from being saved:</p>
        <div class="error-box-message">
          <ul>
          <% @book.errors.full_messages.each do |massage| %>
          <li><%= massage %></li>
          <% end %>
          </ul>
        </div>
      </div>
    <% end %>

  <!--エラーありなしで分岐している-->
    <div class="create-form">
      <%= form_with model: @book, url: books_path, method: :post do |f| %>
        <% if @book.errors.where(:title).empty? %> <!-- エラーがない場合 -->
          <p class="create-form-title">Title<p>
          <%= f.text_field :title , class:"text-area" %>
        <% else %> <!-- エラーがある場合 -->
          <p class="create-form-title create-form-error-title">Title</p>
          <div class="create-form-error-box">
            <%= f.text_field :title , class:"text-area" %>
          </div>
        <% end %>

        <% if @book.errors.where(:body).empty? %> <!-- エラーがない場合 -->
          <p class="create-form-title">Body</p>
          <%= f.text_area :body , class:"text-area" %>
        <% else %> <!-- エラーがある場合 -->
          <p class="create-form-title create-form-error-title">Body</p>
          <div class="create-form-error-box">
            <%= f.text_area :body , class:"text-area" %>
          </div>
        <% end %>
        <div class="create-book-button">
          <%= f.submit "Create Book", class:"submit-button" %>
        </div>
      <% end %>
    </div>
  </div>
</main>

bookers1/app/views/books/show.html.erb
<!--フラッシュメッセージを状況に応じて表示させる-->
<div class="show-box">
  <% if flash[:notice] %>
    <%= content_tag :div, flash[:notice], class: "notice"%>
    <% flash.delete(:notice) %>
  <% end %>
  
<!--レコードの表示-->
<p class="show-title">Title: <span class="show-text"><%= @book.title %></span></p>
<p class="show-body">Body: <span class="show-text"><%= @book.body %></span></p>
</div>

<!--各ページへのリンク-->
<div class="show-links">
  <%= link_to "Edit", edit_book_path(@book.id)%>
  <span class="show-links-line">|</span>
  <%= link_to "Back", books_path %>
</div>

bookers1/app/views/homes/top.html.erb
<header>
  <h2>ようこそBookersへ！</h2>
</header>

<main>
  <div class="intro">
    <p class="intro-text"><span class="bookers">Bookers</span>では、さまざまな書籍に関するあなたの意見や</p>
    <p class="intro-text">印象を共有し交換することができます</p>
    
    <!--一覧ページへのリンク  -->
    <div class="intro-button">
    <%= link_to "start", books_path %>
    </div>
  </div>
</main>

bookers1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>